#+TITLE:configure-commands

* NAME

configure-commands - configure commands for various programs

* TIPS

When a =./configure= says it found something but it doesn't work because it
wasn't able to build a test program with it, go look at the logs.  That test
program may be using a specific feature that needs to be activated.  See
NCURSES.

Look at what Spack does with =spack edit PACKAGE=

When a configure command fails, it will suggest to look at =config.log=.
This is where the output of a compilation test can be found.  They don't all
succeed, so the first failed one is not necessarily the one we want.

* NCURSES

#+begin_src shell
./configure --prefix=PREFIX --with-termlib --enable-termcap --enable-widec \
            --enable-pc-files --with-pkg-config-libdir=PREFIX/lib/pkgconfig
#+end_src

The =./configure= for tig found ncurses but said it was no good because its
test program uses =libtinfo.{a/so}=.  I had to look at the logs to find that
the error was at linking: =ld: Could not find -ltinfo= which is how I knew to
add =--with-termlib=.

* LYNX

[[https://lynx.invisible-island.net/lynx_help/lynx_help_main.html]]

#+begin_src shell
./configure --with-ssl --prefix=<>
#+end_src

NOTE: Redoing it with =--with-ssl= after doing it without doesn't work.

* VIM

#+begin_src shell
./configure --enable-python3interp=dynamic
#+end_src

* BASH

For =C-l= to clear the screen as it should, BASH needs to be compiled with
ncurses support.  The configure process will test for ncurses and compile
without ncurses support if it is not found.  This is why bash will behave
differently when compiled on a system with =ncurses= installed in system
paths.

Setting ~export LDFLAGS=-L<ncurses-libdir>~ prior to the configure command is
enough to change the behavior.

Using =--with-curses= will make the configure command fail if the test for
ncurses fails.

#+begin_src
./configure --with-curses
#+end_src

* AUTHORS

Philippe Carphin
