#+TITLE:Spack notes

* NAME

spack-notes - Quick reference for things that I always forget about spack

* SYNOPSIS

#+begin_src shell
spack env create NAME [-d directory]
spacktivate NAME
spack spec

spack config edit
spack add PACKAGE_SPEC
spack install [--verbose] [--keep-stage] [--keep-prefix] PACKAGE_SPEC
spack locate PACKAGE
spack build-env PACKAGE -- /bin/sh
spack clean --stage

spack compiler find

spack list NAME|GLOB
spack info PACKAGE

spack repo create DIRECTORY NAMESPACE
spack cd (--repo NAMESPACE | PACKAGE_SPEC)

spack create <package-name> [--namespace NAMESPACE] [--template cmake|make|...]
spack edit <package-name>
spack concretize [--force]
spack reindex
#+end_src

* SETUP

Clone the spack repo.  Note that spack builds all dependencies and links them
with absolute RPATHs therefore once something has been built, it is not
relocalizable.

* CREATING ENVIRONMENTS

- =spack env create NAME=: creates =${spack_repo}/environments/${NAME}/spack.yaml=
- =spacktivate NAME=: "Activates" the environment =NAME=.
- =spack spec=: Shows the resolved tree of packages and their dependencies
  for the active environment.

Use =-d DIRECTORY= to create the environment in a different directory.  This
requires 
* ADDING PACKAGES

Assuming an environment has been activated with =spacktivate ENV=, either run
=spack add PACKAGE_SPEC= or run =spack edit config= and add =PACKAGE_SPEC as
a list item to the =spack.specs= YAML list:

#+begin_src yaml
spack:
  specs:
  - PACKAGE_SPEC
#+end_src

See section =PACKAGE SPECS= for more info on package specs.

* FINDING PACKAGES

- =spack list NAME=:  lists all packages whose name contains =NAME=.  The package
  =netcdf-f= is listed by =spack list netcdf=.

- =spack list GLOB=: lists all packages whose name is fully matched by glob. The
  package =netcdf-f= is not matched by =spack list 'n*cdf'= but it is matched
  by =spack list 'n*cdf*'=.

* INFO ON PACKAGES

- =spack info PACKAGE=: lists information on packages.  Look at this to see what
  variants are available.

* PACKAGE SPECS

Example:

- Compiler: =%=
- Variants: =+= (=~= or =-= to disable a variant)
- Version: =@=

Run =spack help --spec= for more details.

* COMPILERS

[[https://spack.readthedocs.io/en/latest/configuring_compilers.html][Spack doc: Configuring compilers]] contains information about finding compilers
automatically and manual configuration options:

- =spack compiler find= automatically detect available compilers.  It will
  either add things to =~/.spack/packages.yaml= or to the currently active
  environment's config (=${spack}/var/spack/environments/${env}/spack.yaml=)
- Manual compiler configuration can be done by editing one of the files named
  above.
  - We can flags to use for that compiler.
  - We can set a module to load for the compiler.

This is an example showing all the possible keys listed in the above
documentation.  It is not an example of a valid or good configuration.
#+begin_src yaml
packages:
  intel-oneapi-compilers:
    externals:
    - spec: intel-oneapi-compilers@2025.1.0
      prefix: /opt/intel/oneapi
      extra_attributes:
        compilers:
          c: /opt/intel/oneapi/compiler/2025.1/bin/icx
          cxx: /opt/intel/oneapi/compiler/2025.1/bin/icpx
          fortran: /opt/intel/oneapi/compiler/2025.1/bin/ifx
        flags:
          cflags: -O3 -fPIC
          cxxflags: -O3 -fPIC
          cppflags: -O3 -fPIC
        environment:
          set:
            MKL_ROOT: "/path/to/mkl/root"
          unset: # A list of environment variables to unset
          - CC
          prepend_path: # Similar for append|remove_path
            LD_LIBRARY_PATH: /ld/paths/added/by/setvars/sh
        extra_rpaths:
        - /path/to/some/compiler/runtime/directory
        - /path/to/some/other/compiler/runtime/directory
      modules: [gcc/10.5.0]
#+end_src

* REPOSITORIES

[[https://spack.readthedocs.io/en/latest/repositories.html][Repositories]]

Create a package repository with the given namespace in the given
directory.
#+begin_src shell
spack repo create DIRECTORY NAMESPACE
#+end_src

Since git repos can contain multiple spack package repos, the following file
at the root of a git repo is necessary
(see [[https://spack.readthedocs.io/en/latest/repositories.html#git-repositories-need-a-package-repo-index][Git repositories need a package repo index]])
#+begin_src yaml
repo_index:
  paths:
  - dir/that/contains/the/repo.yaml/file
#+end_src

Go to the directory of a repository:
#+begin_src shell
spack cd --repo NAMESPACE
#+end_src

When moving packages from one repo to another, an environment may have some kind
of reference to the original location, use
#+begin_src shell
spack concretize --force
#+end_src
to fix that.

* PACKAGE

Packages can be created with
#+begin_src shell
spack create <package-name> [--namespace NAMESPACE] [--template cmake|make|...]
#+end_src
this creates a directory =package_name= containing a file =package.py= with a
class =PackageName=.

Edit the package file with
#+begin_src shell
spack edit <package-name>
#+end_src

See [[https://spack.readthedocs.io/en/latest/packaging_guide_build.html#packaging-workflow-and-commands][Packaging workflow and commands]] explains the edit-install loop with commands
to keep the staging directory (source), keep the install prefix when the build
fails, locate and CD to the staging source dir, and see the environment for the
build:
#+begin_src shell
spack edit mypackage
spack install [--verbose] [--keep-stage] [--keep-prefix] PACKAGE_SPEC

spack locate mypackage
spack cd mypackage
spack build-env mypackage -- /bin/sh
spack clean --stage
#+end_src


A working =package.py= file for a CMake package:
#+begin_src python
class Repos(CMakePackage):
    """Helper tools for managing repositories"""
    homepage = "https://gitlab.com/philippecarphin/repos"
    git = "https://gitlab.com/philippecarphin/repos.git"
    maintainers("philippecarphin")
    license("UNKNOWN", checked_by="philippecarphin")
    version("1.7.0")
    depends_on("go", type="build")
    depends_on("pandoc", type="build")
    depends_on("python@3.8:", type="run")
    depends_on("py-pyyaml", type="run")
#+end_src

* PATCHES

Try not to change patches after having tried things.  If hit with the "could not
find path for package X with sha SOME-SHA, suggest concretize --force" and doing
"concretize --force" does nothing, then
#+begin_src shell
spack edit X # comment the `patch("filename")` line
spack concretize --force
#+end_src

* MISC

If deleting stuff in =${spack}/opt/${arch}=, then the file
=${spack}/opt/spack/.spack-db/index.json= will cause spack to complain that
something in =${spack}/opt/${arch}= is missing.  Edit the JSON file to remove
any reference to what is missing or delete the file altogether.  Deleting the
file may cause *a lot* of work to be redone.

Try =spack reindex=.
