#+TITLE:Spack notes

* NAME

spack-notes - Quick reference for things that I always forget about spack

* SYNOPSIS

#+begin_src shell
spack env create NAME
spacktivate NAME
spack config edit
spack compiler find
spack list NAME|GLOB
spack info PACKAGE
#+end_src

* SETUP

Clone the spack repo.  Note that spack builds all dependencies and links them
with absolute RPATHs therefore once something has been built, it is not
relocalizable.

* CREATING ENVIRONMENTS

- =spack env create NAME= creates =${spack_repo}/environments/${NAME}/spack.yaml=

* ADDING PACKAGES

Assuming an environment has been activated with =spacktivate ENV=,

#+begin_src shell
spack add PACKAGE_SPEC
# or
spack config edit
#+end_src

#+begin_src yaml
spack:
  # add package specs to the `specs` list
  specs:
  - PACKAGE-SPEC
#+end_src

* FINDING PACKAGES

=spack list NAME= lists all packages whose name contains =NAME=.  The package
=netcdf-f= is listed by =spack list netcdf=.

=spack list GLOB= lists all packages whose name is fully matched by glob. The
package =netcdf-f= is not matched by =spack list 'n*cdf'= but it is matched
by =spack list 'n*cdf*'=.

* INFO ON PACKAGES

=spack info PACKAGE= lists information on packages.  Look at this to see what
variants are available.

* PACKAGE SPECS

Example:

- Compiler: =%=
- Variants: =+= (=~= or =-= to disable a variant)
- Version: =@=

Run =spack help --spec= for more details.
