#+TITLE:Spack notes

* NAME

spack-notes - Quick reference for things that I always forget about spack

* SYNOPSIS

#+begin_src shell
spack env create NAME
spacktivate NAME
spack spec

spack config edit
spack add PACKAGE_SPEC

spack compiler find

spack list NAME|GLOB
spack info PACKAGE
#+end_src

* SETUP

Clone the spack repo.  Note that spack builds all dependencies and links them
with absolute RPATHs therefore once something has been built, it is not
relocalizable.

* CREATING ENVIRONMENTS

- =spack env create NAME=: creates =${spack_repo}/environments/${NAME}/spack.yaml=
- =spacktivate NAME=: "Activates" the environment =NAME=.
- =spack spec=: Shows the resolved tree of packages and their dependencies
  for the active environment.

* ADDING PACKAGES

Assuming an environment has been activated with =spacktivate ENV=, either run
=spack add PACKAGE_SPEC= or run =spack edit config= and add =PACKAGE_SPEC as
a list item to the =spack.specs= YAML list:

#+begin_src yaml
spack:
  specs:
  - PACKAGE_SPEC
#+end_src

See section =PACKAGE SPECS= for more info on package specs.

* FINDING PACKAGES

- =spack list NAME=:  lists all packages whose name contains =NAME=.  The package
  =netcdf-f= is listed by =spack list netcdf=.

- =spack list GLOB=: lists all packages whose name is fully matched by glob. The
  package =netcdf-f= is not matched by =spack list 'n*cdf'= but it is matched
  by =spack list 'n*cdf*'=.

* INFO ON PACKAGES

- =spack info PACKAGE=: lists information on packages.  Look at this to see what
  variants are available.

* PACKAGE SPECS

Example:

- Compiler: =%=
- Variants: =+= (=~= or =-= to disable a variant)
- Version: =@=

Run =spack help --spec= for more details.
