#+TITLE:Spack notes

* NAME

spack-notes - Quick reference for things that I always forget about spack

* SYNOPSIS

#+begin_src shell
spack env create NAME
spacktivate NAME
spack spec

spack config edit
spack add PACKAGE_SPEC

spack compiler find

spack list NAME|GLOB
spack info PACKAGE
#+end_src

* SETUP

Clone the spack repo.  Note that spack builds all dependencies and links them
with absolute RPATHs therefore once something has been built, it is not
relocalizable.

* CREATING ENVIRONMENTS

- =spack env create NAME=: creates =${spack_repo}/environments/${NAME}/spack.yaml=
- =spacktivate NAME=: "Activates" the environment =NAME=.
- =spack spec=: Shows the resolved tree of packages and their dependencies
  for the active environment.

* ADDING PACKAGES

Assuming an environment has been activated with =spacktivate ENV=, either run
=spack add PACKAGE_SPEC= or run =spack edit config= and add =PACKAGE_SPEC as
a list item to the =spack.specs= YAML list:

#+begin_src yaml
spack:
  specs:
  - PACKAGE_SPEC
#+end_src

See section =PACKAGE SPECS= for more info on package specs.

* FINDING PACKAGES

- =spack list NAME=:  lists all packages whose name contains =NAME=.  The package
  =netcdf-f= is listed by =spack list netcdf=.

- =spack list GLOB=: lists all packages whose name is fully matched by glob. The
  package =netcdf-f= is not matched by =spack list 'n*cdf'= but it is matched
  by =spack list 'n*cdf*'=.

* INFO ON PACKAGES

- =spack info PACKAGE=: lists information on packages.  Look at this to see what
  variants are available.

* PACKAGE SPECS

Example:

- Compiler: =%=
- Variants: =+= (=~= or =-= to disable a variant)
- Version: =@=

Run =spack help --spec= for more details.

* COMPILERS

[[https://spack.readthedocs.io/en/latest/configuring_compilers.html][Spack doc: Configuring compilers]] contains information about finding compilers
automatically and manual configuration options:

- =spack compiler find= automatically detect available compilers.  It will
  either add things to =~/.spack/packages.yaml= or to the currently active
  environment's config (=${spack}/var/spack/environments/${env}/spack.yaml=)
- Manual compiler configuration can be done by editing one of the files named
  above.
  - We can flags to use for that compiler.
  - We can set a module to load for the compiler.

This is an example showing all the possible keys listed in the above
documentation.  It is not an example of a valid or good configuration.
#+begin_src yaml
packages:
  intel-oneapi-compilers:
    externals:
    - spec: intel-oneapi-compilers@2025.1.0
      prefix: /opt/intel/oneapi
      extra_attributes:
        compilers:
          c: /opt/intel/oneapi/compiler/2025.1/bin/icx
          cxx: /opt/intel/oneapi/compiler/2025.1/bin/icpx
          fortran: /opt/intel/oneapi/compiler/2025.1/bin/ifx
        flags:
          cflags: -O3 -fPIC
          cxxflags: -O3 -fPIC
          cppflags: -O3 -fPIC
        environment:
          set:
            MKL_ROOT: "/path/to/mkl/root"
          unset: # A list of environment variables to unset
          - CC
          prepend_path: # Similar for append|remove_path
            LD_LIBRARY_PATH: /ld/paths/added/by/setvars/sh
        extra_rpaths:
        - /path/to/some/compiler/runtime/directory
        - /path/to/some/other/compiler/runtime/directory
      modules: [gcc/10.5.0]
#+end_src
