* #+TITLE:tmux-notes

* NAME

tmux-notes - Notes on TMUX

* PANE MANIPULATION

- *marking*: =select-pane -m= (toggles marking) Default binding =prefix m=
- *locking*: =select-pane -d= No default binding, unlock with =select-pane
  -e=
- *joining*: =join-pane [-h]= Splits the current pane [vertically] and moves the
  marked pane into the new split instead of starting a new shell.

* MISC

- =-h= for horizontal:  The dividing line is vertical but the panes are next
  to each other horizontally.
* GETTING VALUES

** Options

In general, =tmux show= but we need to know what scope the thing we want to
see is in.  For example:
- =default-command=: =tmux show -g default-command=

** Variables

The list of variables is available in the *FORMAT* section of =man tmux= but
if I want the value of some variable like "where is the socket for this tmux
session?", then I can use =display-message= to see it:

- =tmux display-message -p '#{VARIABLE_NAME}'= where =VARIABLE_NAME= is the name
  of a TMUX variable.  The =-p= makes the message appear on STDOUT of the
  shell running the command instead of in the message area of the TMUX
  client.
